import Head from "next/head";
import styles from "../styles/Home.module.css";
import ArrowBackTwoToneIcon from "@mui/icons-material/ArrowBackTwoTone";
import { IconButton } from "@mui/material";
import { connect } from "react-redux";
import { useRouter } from "next/router";

function page3(props) {
	const router = useRouter();
	return (
		<div className={styles.container}>
			<Head>
				<title>Genderize me!</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/img/equality.png" />
			</Head>

			<main className={styles.main}>
				<IconButton className={styles.backArrow} onClick={() => router.back()}>
					<ArrowBackTwoToneIcon />
				</IconButton>
				<video
					autoPlay
					muted
					loop
					className={styles.video}
					src="/video.mp4"
					type="video/mp4"
				></video>
				<div className={styles.formBox}>
					<div style={{ textAlign: "center" }}>
						<h1 id="title">Result for: {props.firstName}</h1>
					</div>
					<div className={styles.formBoxP2}>
						<div style={{ margin: 20 }}>
							<p>
								<span style={{ fontWeight: "bold" }}>First Name: </span>{" "}
								{props.firstName}
							</p>
							<p>
								<span style={{ fontWeight: "bold" }}>Gender: </span>
								{props.gender}
							</p>
						</div>
						<div style={{ margin: 20 }}>
							<p>
								<span style={{ fontWeight: "bold" }}>Last Name: </span>{" "}
								{props.lastName}
							</p>
							<p>
								<span style={{ fontWeight: "bold" }}>Age: </span>
								{props.age}
							</p>
						</div>
					</div>
				</div>
			</main>
		</div>
	);
}

function mapStateToProps(state) {
	return {
		firstName: state.inputInfos.firstName,
		lastName: state.inputInfos.lastName,
		age: state.specs.age,
		gender : state.specs.gender,
	};
}

export default connect(mapStateToProps, null)(page3);
